version: '3'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'
  kafka:
    build:
      context: ./Kafka
      dockerfile: Dockerfile
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  producer:
    build:
      context: ./Producer
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - './Producer:/app'
    working_dir: '/app'
    depends_on:
      - zookeeper
      - kafka
  consumer:
    image: 'maven:latest'
    working_dir: '/app'
    ports:
      - '8080:8080'
    volumes:
      - './Consumer:/app'
    depends_on:
      - zookeeper
      - kafka