version: '3'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  producer:
    image: 'python:latest'
    ports:
      - '5000:5000'
    volumes:
      - './Producer:/app'
    working_dir: '/app'
    command: bash -c "pip install -r requirements.txt && python app.py"
  consumer:
    image: 'maven:latest'
    working_dir: '/app'
    ports:
      - '8080:8080'
    volumes:
      - './Consumer:/app'