version: '3'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.4.3'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'
  kafka:
    build:
      context: ./Kafka
      dockerfile: Dockerfile
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  producers:
    build:
      context: ./Producers
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - './Producers:/service'
    working_dir: '/service'
    depends_on:
      - zookeeper
      - kafka
  consumers:
    build:
      context: ./Consumers
      dockerfile: Dockerfile
    working_dir: '/service'
    environment:
      KAFKA_SERVER: kafka:9092
    volumes:
      - './Consumers:/service'
    depends_on:
      - zookeeper
      - kafka