FROM confluentinc/cp-kafka:7.4.3
LABEL org.opencontainers.image.description="Create two topics and expose zookeeper connection ports to Docker network instead of local"

COPY server.properties /etc/kafka/server.properties
COPY kafka_init.sh /kafka_init.sh
EXPOSE 9092
CMD ["/kafka_init.sh"]